/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as FichaRouteImport } from './routes/ficha'
import { Route as FuentesRouteImport } from './routes/fuentes'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as TarjetasRouteImport } from './routes/tarjetas'
import { Route as EstudioIndexRouteImport } from './routes/estudio/index'
import { Route as EstudioSlugRouteImport } from './routes/estudio/$slug'
import { Route as PracticaIndexRouteImport } from './routes/practica/index'
import { Route as PracticaBankRouteImport } from './routes/practica/$bank'
import { Route as SimulacroIndexRouteImport } from './routes/simulacro/index'
import { Route as SimulacroExamenRouteImport } from './routes/simulacro/examen'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaRoute = FichaRouteImport.update({
  id: '/ficha',
  path: '/ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const FuentesRoute = FuentesRouteImport.update({
  id: '/fuentes',
  path: '/fuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioIndexRoute = EstudioIndexRouteImport.update({
  id: '/estudio/',
  path: '/estudio/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioSlugRoute = EstudioSlugRouteImport.update({
  id: '/estudio/$slug',
  path: '/estudio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaIndexRoute = PracticaIndexRouteImport.update({
  id: '/practica/',
  path: '/practica/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaBankRoute = PracticaBankRouteImport.update({
  id: '/practica/$bank',
  path: '/practica/$bank',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroIndexRoute = SimulacroIndexRouteImport.update({
  id: '/simulacro/',
  path: '/simulacro/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroExamenRoute = SimulacroExamenRouteImport.update({
  id: '/simulacro/examen',
  path: '/simulacro/examen',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/ficha': typeof FichaRoute
  '/fuentes': typeof FuentesRoute
  '/guia': typeof GuiaRoute
  '/progreso': typeof ProgresoRoute
  '/tarjetas': typeof TarjetasRoute
  '/estudio/$slug': typeof EstudioSlugRoute
  '/practica/$bank': typeof PracticaBankRoute
  '/simulacro/examen': typeof SimulacroExamenRoute
  '/estudio/': typeof EstudioIndexRoute
  '/practica/': typeof PracticaIndexRoute
  '/simulacro/': typeof SimulacroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/ficha': typeof FichaRoute
  '/fuentes': typeof FuentesRoute
  '/guia': typeof GuiaRoute
  '/progreso': typeof ProgresoRoute
  '/tarjetas': typeof TarjetasRoute
  '/estudio/$slug': typeof EstudioSlugRoute
  '/practica/$bank': typeof PracticaBankRoute
  '/simulacro/examen': typeof SimulacroExamenRoute
  '/estudio': typeof EstudioIndexRoute
  '/practica': typeof PracticaIndexRoute
  '/simulacro': typeof SimulacroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cargo': typeof CargoRoute
  '/ficha': typeof FichaRoute
  '/fuentes': typeof FuentesRoute
  '/guia': typeof GuiaRoute
  '/progreso': typeof ProgresoRoute
  '/tarjetas': typeof TarjetasRoute
  '/estudio/$slug': typeof EstudioSlugRoute
  '/practica/$bank': typeof PracticaBankRoute
  '/simulacro/examen': typeof SimulacroExamenRoute
  '/estudio/': typeof EstudioIndexRoute
  '/practica/': typeof PracticaIndexRoute
  '/simulacro/': typeof SimulacroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cargo'
    | '/ficha'
    | '/fuentes'
    | '/guia'
    | '/progreso'
    | '/tarjetas'
    | '/estudio/$slug'
    | '/practica/$bank'
    | '/simulacro/examen'
    | '/estudio/'
    | '/practica/'
    | '/simulacro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cargo'
    | '/ficha'
    | '/fuentes'
    | '/guia'
    | '/progreso'
    | '/tarjetas'
    | '/estudio/$slug'
    | '/practica/$bank'
    | '/simulacro/examen'
    | '/estudio'
    | '/practica'
    | '/simulacro'
  id:
    | '__root__'
    | '/'
    | '/cargo'
    | '/ficha'
    | '/fuentes'
    | '/guia'
    | '/progreso'
    | '/tarjetas'
    | '/estudio/$slug'
    | '/practica/$bank'
    | '/simulacro/examen'
    | '/estudio/'
    | '/practica/'
    | '/simulacro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargoRoute: typeof CargoRoute
  FichaRoute: typeof FichaRoute
  FuentesRoute: typeof FuentesRoute
  GuiaRoute: typeof GuiaRoute
  ProgresoRoute: typeof ProgresoRoute
  TarjetasRoute: typeof TarjetasRoute
  EstudioSlugRoute: typeof EstudioSlugRoute
  PracticaBankRoute: typeof PracticaBankRoute
  SimulacroExamenRoute: typeof SimulacroExamenRoute
  EstudioIndexRoute: typeof EstudioIndexRoute
  PracticaIndexRoute: typeof PracticaIndexRoute
  SimulacroIndexRoute: typeof SimulacroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha': {
      id: '/ficha'
      path: '/ficha'
      fullPath: '/ficha'
      preLoaderRoute: typeof FichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuentes': {
      id: '/fuentes'
      path: '/fuentes'
      fullPath: '/fuentes'
      preLoaderRoute: typeof FuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio/': {
      id: '/estudio/'
      path: '/estudio'
      fullPath: '/estudio/'
      preLoaderRoute: typeof EstudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio/$slug': {
      id: '/estudio/$slug'
      path: '/estudio/$slug'
      fullPath: '/estudio/$slug'
      preLoaderRoute: typeof EstudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica/': {
      id: '/practica/'
      path: '/practica'
      fullPath: '/practica/'
      preLoaderRoute: typeof PracticaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica/$bank': {
      id: '/practica/$bank'
      path: '/practica/$bank'
      fullPath: '/practica/$bank'
      preLoaderRoute: typeof PracticaBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro/': {
      id: '/simulacro/'
      path: '/simulacro'
      fullPath: '/simulacro/'
      preLoaderRoute: typeof SimulacroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro/examen': {
      id: '/simulacro/examen'
      path: '/simulacro/examen'
      fullPath: '/simulacro/examen'
      preLoaderRoute: typeof SimulacroExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargoRoute: CargoRoute,
  FichaRoute: FichaRoute,
  FuentesRoute: FuentesRoute,
  GuiaRoute: GuiaRoute,
  ProgresoRoute: ProgresoRoute,
  TarjetasRoute: TarjetasRoute,
  EstudioSlugRoute: EstudioSlugRoute,
  PracticaBankRoute: PracticaBankRoute,
  SimulacroExamenRoute: SimulacroExamenRoute,
  EstudioIndexRoute: EstudioIndexRoute,
  PracticaIndexRoute: PracticaIndexRoute,
  SimulacroIndexRoute: SimulacroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
